name: Deploy via SSH to Windows

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Windows via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull anish0910/portfolio:latest
            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d --name portfolio -p 80:80 anish0910/portfolio:latest
